### ISSUE TITLE
Final step labelled as None

### ISSUE THREAD

**Issue by JPDarby** [ACEsuit/ACEHAL#11]
`HAL iter 51 got config with criterion 0.07172618293682953 at time step None / 2000`

If the final step is reached without triggering the tolerance it gets reported as `None`

**Comment by bernstei** [comment]
Well, the information is there, if you know that None means final step :)

I'm cleaning up all that output - I hope to push some fixes soon.

**Comment by JPDarby** [comment]
Very true and thanks! + definitely not a big deal I'm just being trigger happy with raising issues to keep track of things :)

**Comment by casv2** [comment]
Keep them coming!

**Comment by bernstei** [comment]
Cleaned up in 81ce4b0, without a PR.  If it looks OK, can you close the issue?
