### ISSUE TITLE
Excluding large forces from training / test error reports

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACEHAL#24]
Occasionally the trian/test errors can look strange if a large force component greater than 'Fmax' is included in the train/test database. This can skew the error table considerably, while the actual model itself typically runs very well and has good generalisation on 'normal' forces. 

@bernstei What are your thoughts on excluding these forces (and perhaps the total energy too) from training and test? It has confused me and I'm sure it may do so for others too.

**Comment by cortner** [comment]
I would love to figure out a general way to rescale forces and target some kind of relative force accuracy.

**Comment by bernstei** [comment]
Yes, I agree that it's pretty reasonable to apply Fmax also to the reported errors (in addition to excluding them from the fit, which is already being done). 

@cortner that's a separate issue, and I think can be handled by a per-force weight that's inversely proportional to the force.  However, it needs to be regularized near |F|=0, and when I tried it for phonon fitting I got extremely ill-conditioned problems.

**Comment by gabor1** [comment]
> I would love to figure out a general way to rescale forces and target some kind of relative force accuracy.

I agree. We said some time ago that this is a nonlinear problem and one can only do it iteratively, adjusting weights and watching relative force accuracies move. with a cached design matrix, maybe not impossible?

**Comment by gabor1** [comment]
It would also be nice to report how many force components got excluded because of > Fmax criterion (and remind the user what Fmax was used)

**Comment by bernstei** [comment]
> It would also be nice to report how many force components got excluded because of > Fmax criterion (and remind the user what Fmax was used)

@gabor1 Do you think this should happen during the fit, or error-table construction (what this issue is technically about), or both?

**Comment by bernstei** [comment]
Take a look at the print I added to the matrix-assembly stage of fitting.

**Comment by gabor1** [comment]
Both maybe?

Gábor Csányi
Professor of Molecular Modelling
Engineering Laboratory, University of Cambridge
Pembroke College Cambridge

Pembroke College supports CARA. A Lifeline to Academics at Risk.  http://www.cara.ngo/


On 20 Sep 2023, at 21:29, bernstei ***@***.***> wrote:

﻿

Take a look at the print I added to the matrix-assembly stage of fitting.
