### ISSUE TITLE
allow configs to specify their HAL traj params

### ISSUE THREAD

**Issue by bernstei** [ACEsuit/ACEHAL#3]
Let HAL use `Atoms.info` to set parameters (overriding explicitly passed in arguments) for particular initial configs.

- traj_len
- temperature_K
- P_GPa

Anything else, @casv2 ?
- tau_rel? 
 
 Should we package those parameters into a dict, and have HAL receive that instead of individual arguments?

**Comment by casv2** [comment]
I think so, packaging as a dict and ability to override tau_rel and perhaps tol could be useful functionality. I’m not sure we’d be using them often though

**Comment by bernstei** [comment]
Good point about tol. I'll also implement the possibility of a ramp for tau_rel.  Let me put together a PR.

**Comment by casv2** [comment]
I guess ultimately we will want to include global importance weights per config type too. The E/F/V weights we would then start tuning based on the residuals

**Comment by bernstei** [comment]
That gets a tiny bit uglier, since it reaches inside `fit_kwargs`, but it's perfectly doable, yes. However, I think we might be better off extending our ARD/BRR to have 3 separate var_e, one for each type of quantity, rather than hand-fiddling with E/F/V weights.  Chuck and I have discussed that, and we don't think it'll be hard to add.

**Comment by casv2** [comment]
This is what I meant actually, and I agree. I meant one level "up" e.g. `1.0` for a solid and `0.6` for a liquid as a global importance weight. But maybe by optimising the var_e this already is effectively achieved.
