### ISSUE TITLE
r_0, r_in estimate and julia_source functionality?

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACEHAL#6]
Do we still need these functions as the new defaults in ACE1pack already take care of this?

@bernstei

**Comment by bernstei** [comment]
I guess we don't have any use for them now, and we can always revive it from git history.  Maybe move them to some sort of Attic directory, so we remember it exists?  I can do that.

**Comment by casv2** [comment]
OK, sounds good

**Comment by casv2** [comment]
Wait same goes for the julia_source basis interface? Maybe we can "hardcode" the current basis back in and just change smoothness priors. All heuristics go into ACE1pack. We'd change heuristics there and update our `tomls` in this repo separately.

**Comment by bernstei** [comment]
I really like being able to experiment with a new basis just by passing julia source, and it's a trivial amount of code complexity in my opinion, so I'd rather leave that in.

**Comment by casv2** [comment]
Sure, let's keep it

**Comment by bernstei** [comment]
I'll do this once your PR updating the basis is merged and we no longer need that function in the tests.

**Comment by casv2** [comment]
Done in #4
