### ISSUE TITLE
swap MC steps

### ISSUE THREAD

**Issue by casv2** [ACEsuit/ACEHAL#8]
Addition of swap MC steps using `SwapMC`. The MC accept/reject function can then be filtered out of `CellMC` and shared.

**Comment by bernstei** [comment]
I could go either way.  We could make it a more generic `MDMCMoves` class.

**Comment by bernstei** [comment]
That feels like it'll result in less code duplication.  I guess it would become somewhat more complex (e.g. constructor arguments), but not so much that I think it's a problem.

**Comment by bernstei** [comment]
I guess the one thing about having separate objects is that they can be called at different frequencies.   Maybe it's worth it for that.

**Comment by casv2** [comment]
Yes separate frequencies make sense I think, P+R solving this coming in soon

**Comment by casv2** [comment]
#9 should solve this

**Comment by casv2** [comment]
solved
